server:
  port: 8080

spring:
  application:
    name: expense-tracker

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/expense-tracker
    username: 'amigoscode'
    password: 'password'